/**
 * Copyright 2010 Molindo GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_molindo_mysqlcollations_lib_CollationCompare */

#ifndef _Included_at_molindo_mysqlcollations_lib_CollationCompare
#define _Included_at_molindo_mysqlcollations_lib_CollationCompare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_molindo_mysqlcollations_lib_CollationCompare
 * Method:    index
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_molindo_mysqlcollations_lib_CollationCompare_index
  (JNIEnv *, jclass, jstring);

/*
 * Class:     at_molindo_mysqlcollations_lib_CollationCompare
 * Method:    compareBytes
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_at_molindo_mysqlcollations_lib_CollationCompare_compareBytes
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
